spring:
  ai:
    openai:
      api-key: your-deepseek-apikey
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.5
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: your-redis-password
      timeout: 3000
      jedis:
        pool:
          # 连接池中的最大空闲连接
          max-idle: 500
          # 连接池中的最小空闲连接
          min-idle: 50
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 2000
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: 1000

my:
  version: 1.0.0
  author: Ricky
  amap:
    api-key: your-amap-apikey
  tongyi:
    api-key: your-tongyi-apikey
